set tabstop=2
syntax enable
set background=dark
colorscheme molokai
set encoding=utf8
set smartindent
set number
set mouse=a
set cursorline
set laststatus=2
set noswapfile
set expandtab
set shiftwidth=2
